config/routes.rb
IlinkolnBlog::Application.routes.draw do
  

  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure"            => "sessions#failure" 
  match "/signout"                 => "sessions#destroy", :as => :signout
  match "/events"                  => "pages#events"
  match "/about_us"                => "pages#about_us"
  match "/contact_us"              => "pages#contact_us"
  match "/lincoln_hack"            => "pages#lincoln_hack"
  
  resources :categories
  resources :members
  resources :posts do
    resources :comments
  end
  
  
  
  

   root :to => "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to  :member
  belongs_to  :category
  
  validates   :category_id, :presence => true
  validates   :body,        :presence => true 
  validates   :title ,      :presence => true,
                            :length   => { :minimum => 4 }
  
  has_many    :comments,    :dependent => :destroy
  
  def to_param
    "#{id}-#{slug}"
  end
  
  def slug
    self.title.downcase.gsub(/[^a-z0-9]/, '-')
  end
  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_filter :authorize, :except => [ :index, :show ]
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all(:order => "created_at DESC")
    @title = "#{@posts.first.title}" if @posts.any?

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
      format.atom { render :layout => false }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])
    @title = @post.title

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @title = "Post a new blog"
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @title = "Editing #{@post.title}"
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.create! params[:post].merge(:member_id => current_member.id )

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <%= f.label :title, "Article Title" %><br />
    <%= f.text_field :title, :required => true %>
	</div>
	<div class="field">
    <%= f.label :body, "Article " %><br />
    <%= f.text_area :body, :required => true %>
	</div>
	<div class="field">
		<ul>
			<li><h2>Category</h2></li>
	    <% Category.all.each do |category| %>
			<li>
	    		<label><%= f.radio_button :category_id, category.id%><label> <%= category.name.titleize %></label>
	  		</li>
		<% end -%>
		</ul>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<article class="article">

		<h1><%= link_to "#{post.title}", post, :title => "#{post.title}" %></h1>
		<h2>
			 <%= post.created_at.strftime('%b %d, %Y') %> &bull; By: Nelson Kelem
				&bull; Category: 
				<%= link_to "#{post.category.name}", categories_path(@category), :title => "view all articles in this category" %>
				
				
				<%= link_to	raw("<span class=\"point\"></span>
								<em> #{h post.comments.count} Comments</em>"), 
								@post, :class => "speech-bubl", :title => "Read Comments" %>
		</h2>
		<%= kramdown truncate(post.body, :length => 500, :omission =>'[...]') %>
		<p>
		<% if admin? %>
			<%= link_to 'New Post', new_post_path %> | 
			<%= link_to 'Edit Post', edit_post_path(post) %> | 
			<%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %>
		<% end %>
		</p>
	</article>
<% end %>

app/views/posts/new.html.erb
<h1>New post <%= link_to  'Back to all posts', posts_path, :class => "float_rt" %></h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<article class="article">	
	<h1><%= @post.title %></h1>
	<h2>
		 <%= @post.created_at.strftime('%b %d, %Y') %> &bull; By:
			<%= link_to "#{@post.member.name}", member_path(@post.member), :title => "view member profile" %>
			&bull; Category: 
			<%= link_to "#{@post.category.name}", categories_path(@category), :title => "view all articles in this category" %>
			<a href="#" title="Read comments" class="speech-bubl" >
				<span class="point"></span>
				<em> <%= @post.comments.count %> Comments</em>
			</a>
			
	</h2>
	<%= kramdown(@post.body) %>
	
	<% if admin? %>
	<div class="controls">
		<p>
			<%= link_to 'Edit This Post', edit_post_path(@post) %> | 
			<%= link_to 'Back', posts_path %> | 
			<%= link_to 'Destroy', @post, :method => :delete, :confirm => "Are you sure?" %>
		</p>
	</div>
	<% end %>
</article>


<h2 class="hr">Comments</h2>
	<ul id="comment-list"  >
		<% @post.comments.each do |comment| %>
		<li>
			<div class="comment">
				<%= kramdown comment.body %>
			<% if admin? %>
			<p>
			<%= link_to 'Destroy Comment', [comment.post, comment],
				 		:confirm	=> 'Are you sure?',
						:method		=> :delete %>
			
			</p>
			<% end %>
			
			</div><!-- end .comment -->
			
			<div class="commentor">
				<%= link_to "#{truncate comment.commenter}", "http://www.safarista.com/blog", :target => "_blank", :rel => "nofollow" %>
				<p><small><%= comment.created_at.to_date %></small></p>
			</div>
		</li>
		<% end %>
	
	</ul><!-- end #comment-list -->
	
	<div id="comment-form">
		<h2 class="hr">add a comment</h2>
		<p>
			I welcome your comments on this article. Please complete the form below to add to the conversation.
		</p>
		<p>
			<strong>Note:</strong>
			I reserve the right to edit or remove any comment that is deemed inappropriate, off-topic, or offensive.
		</p>
		
		<%= form_for([@post, @post.comments.build]) do |f| %>
			
			<p>
				<%= f.label      	:commenter, "Commenter" %> <br>
				<% if signed_in? %>
				<%= f.text_field 	:commenter, :value => current_member.name, :required => true %>
				<% else %>
				<%= f.text_field 	:commenter, :required =>true %>
				<% end %>
			</p>
			<p>
				<%= f.label      	:email, "Email" %> <br>
				<% if signed_in? %>
				<%= f.email_field 	:email, :value => current_member.contact, :required => true %>
				<% else %>
				<%= f.email_field	:email, :required =>true %>
				<% end %>
			</p>
			<p>
				<%= f.label     	:website, "Website" %> <br>
				<% if signed_in? %>
				<%= f.url_field 	:website, :value => current_member.website, :required => true %>
				<% else %>
				<%= f.url_field		:website, :required =>true %>
				<% end %>
			</p>
			<p>
				<%= f.label     	:body, "Body" %> <br>
				<%= f.text_area 	:body, :required =>true %>
			</p>
			<p>
				<%= f.submit %>
			</p>
		<% end %>
	</div>
	