config/routes.rb
IlinkolnBlog::Application.routes.draw do
  

  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure"            => "sessions#failure" 
  match "/signout"                 => "sessions#destroy", :as => :signout
  match "/events"                  => "pages#events"
  match "/about_us"                => "pages#about_us"
  match "/contact_us"              => "pages#contact_us"
  match "/lincoln_hack"            => "pages#lincoln_hack"
  
  resources :categories
  resources :members
  resources :posts do
    resources :comments
  end
  
  
  
  

   root :to => "posts#index"

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :posts
  attr_protected :admin
  
  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end
  def self.create_with_omniauth(auth)
    create! do |member|
      member.provider     = auth["provider"]
      member.uid          = auth["uid"]
      member.name         = auth["info"]["name"]
      member.location     = auth["info"]["location"]
      member.twitter      = auth["info"]["nickname"]
      member.description  = auth["info"]["description"]
      member.avatar       = auth["info"]["image"]
    end
  end
  
  def to_param
    "#{id}-#{slug}"
  end
  
  def slug
    self.name.downcase.gsub(/[^a-z0-9]/, '-')
  end
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # before_filter :authorize, :except => [:index, :show]
  before_filter :can_modify, :only => [:edit, :update, :destroy] 
  respond_to :html, :xml, :json 
  # GET /members
  # GET /members.xml
  def index
    @members = Member.all(:order => "created_at DESC")
    @title = "This is a list of all members"
    respond_with (@members)
  end

  # GET /members/1
  # GET /members/1.xml
  def show
    @member = Member.find(params[:id])
    @title = "#{@member.name}"
  
    respond_with(@member)
  end
 
  # GET /members/new
  # GET /members/new.xml
  def new
    @member = Member.new
    @title = "Add a new person"

    respond_with(@member)
  end

  # GET /members/1/edit
  def edit
    @title = "Editing #{@member.name}'s details"
        
    
  end

  # # POST /members
  # # POST /members.xml
  # def create
  #   @member = Member.new(params[:member])
  # 
  #   respond_to do |format|
  #     if @member.save
  #       format.html { redirect_to(@member, :notice => 'member was successfully created.') }
  #       format.xml  { render :xml => @member, :status => :created, :location => @member }
  #     else
  #       format.html { render :action => "new" }
  #       format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /members/1
  # PUT /members/1.xml
  def update
    
      if @member.update_attributes(params[:member])
        redirect_to(members_path, :notice => 'Member was successfully updated.')
      else
         render :action => "edit"
      end
  end

  # DELETE /members/1
  # DELETE /members/1.xml
  def destroy
    @member.destroy

    respond_with(@member) { redirect_to(members_url, :notice => 'Member was successfully deleted.') }
    
  end
  
  protected
  def can_modify
    @member = Member.find(params[:id])
    @member = current_member if !admin? 
  end
end

app/helpers/members_helper.rb
module MembersHelper
  # helper_method :owner?
  # 
  # protected
  # def owner?
  #   signed_in? && @member.id == current_member.id
  # end
end

app/views/members/_form.html.erb
<%= form_for @member, :member, :html => { :multipart => true }  do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Your names" %><br />
    <%= f.text_field :name, :required => true %>
  </div>
	<div class="field">
    <%= f.label :avatar, "Your Avatar URL" %><br />
    <%= f.url_field :avatar, :required => true %>
  </div>
	<div class="field">
    <%= f.label :location, "Location" %><br />
    <%= f.text_field :location, :required => true %>
  </div>
	<div class="field">
    <%= f.label :title, "Your Title" %><br />
    <%= f.text_field :title, :required => true %>
  </div>
  <div class="field">
    <%= f.label :company, "Name of your company" %><br />
    <%= f.text_field :company, :required => true %>
  </div>
	<div class="field">
    <%= f.label :contact, "Your contact" %> <i>Either your email.</i><br />
    <%= f.email_field :contact, :required => true %>
  </div>
	<div class="field">
    <%= f.label :website, "Your website" %><br />
    <%= f.url_field :website, :required => true %>
  </div>
	<div class="field">
    <%= f.label :description, "Description of what you do" %><br />
    <%= f.text_area :description, :required => true %>
  </div>
	<div class="field">
    <%= f.label :aboutus, "What is iLinkoln to you? Any changes you would like?" %><br />
    <%= f.text_area :aboutus, :required => true %>
  </div>
  <div class="actions">
    <%= f.submit %> <i>Everything you put here is public</i>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>All members</h1>
<ul  id="members">
<% @members.each do |member| %>
	
	<li itemscope itemtype="http://data-vocabulary.org/Person">
		
		<div  class="float_rt member_info">
			<strong>Name: </strong><span itemprop="name"><%= member.name %></span>
			<br>
			<strong>Location: </strong><span itemprop="adr"><%= member.location %></span>
			<br>
			<strong>Title: </strong><span itemprop="title"><%= member.title %></span>
			<br>
			<strong>Company: </strong><span itemprop="org"><%= member.company %></span>
			<br>
			<strong>Website: </strong><span itemprop="url"><%= member.website %></span>
			<br>	
			<strong>What I do: </strong><div itemprop="description"><%= simple_format truncate(member.description, :length => 500, :omission => "[...]")%></div>
			<br>	
			<div><strong>What I think about iLinkoln: </strong><%= simple_format member.aboutus %></div>
		</div>
		<figure  class="member_img float_lt">
			<%= link_to (image_tag(member.avatar, :size => "140x140")), member,  :itemprop =>"photo" %>
			<figcaption> <%= link_to "@#{member.twitter}", "http://twitter.com/#{member.twitter}", :target => "_blank" %></figcaption>
		</figure>
		<div  class="clearfix">
			<% if @owner %>
			<%= link_to 'Edit', edit_member_path(member) %> | 
			<% if admin? %>
			<%= link_to 'Destroy', member, :confirm => 'Are you sure?', :method => :delete %>
			<% end %>
			<% else %>
			
			<% end %>
		</div>
	</li>
<% end %>
</ul>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<ul  id="members">
	<li itemscope itemtype="http://data-vocabulary.org/person">

		<div  class="float_rt member_info">
			<strong>Name: </strong><span itemprop="name"><%= @member.name %></span>
			<br>
			<strong>Title: </strong><span itemprop="title"><%= @member.title %></span>
			<br>
			<strong>Location: </strong><span itemprop="adr"><%= @member.location %></span>
			<br>
			<strong>Company: </strong><span itemprop="org"><%= @member.company %></span>
			<br>
			<strong>Website: </strong><span><%= link_to @member.website, "#{@member.website}",  :itemprop =>"url", :title => "My website", :target => "_blank" %></span>
			<br>	
			<strong>What I do: </strong><div itemprop="role"><%= kramdown @member.description%></div>
			<br>	
			<div><strong>What I think about iLinkoln: </strong><%= simple_format @member.aboutus %></div>
		</div>
		<figure  class="member_img">
			<%= image_tag @member.avatar, :size => "140x140", :itemprop =>"photo" %>
			<figcaption> <%= link_to "@#{@member.twitter}", "http://twitter.com/#{@member.twitter}", :title => "twitter profile", :target => "_blank", :itemprop => "url" %></figcaption>
		</figure>
		<div  class="clearfix">
			<%= link_to 'Edit', edit_member_path(@member) if admin? or owner? %>
		</div>
	</li>
</ul>